export default [
  {
    emoji: '✨',
    code: ':sparkles:',
    descEN: 'Introduce new features',
    descCN: '引入新功能',
    name: 'sparkles',
    semver: 'minor',
    type: 'feat',
  },
  {
    emoji: '🐛',
    code: ':bug:',
    descEN: 'Fix a bug',
    descCN: '修复 bug',
    name: 'bug',
    semver: 'patch',
    type: 'fix',
  },
  {
    emoji: '♻️',
    code: ':recycle:',
    descEN: 'Refactor code that neither fixes a bug nor adds a feature',
    descCN: '重构代码',
    name: 'recycle',
    semver: 'patch',
    type: 'refactor',
  },
  {
    emoji: '⚡',
    code: ':zap:',
    descEN: 'A code change that improves performance',
    descCN: '提高性能',
    name: 'zap',
    semver: 'patch',
    type: 'perf',
  },
  {
    emoji: '💄',
    code: ':lipstick:',
    descEN: 'Add or update style files that do not affect the meaning of the code',
    descCN: '添加或更新 UI 和样式文件',
    name: 'lipstick',
    semver: 'patch',
    type: 'style',
  },
  {
    emoji: '✅',
    code: ':white_check_mark:',
    descEN: 'Adding missing tests or correcting existing tests',
    descCN: '添加、更新或通过测试',
    name: 'white-check-mark',
    semver: null,
    type: 'test',
  },
  {
    emoji: '📝',
    code: ':memo:',
    descEN: 'Documentation only changes',
    descCN: '添加或更新文档',
    name: 'memo',
    semver: null,
    type: 'docs',
  },
  {
    emoji: '👷',
    code: ':construction_worker:',
    descEN: 'Changes to our CI configuration files and scripts',
    descCN: '添加或更新 CI 构建系统',
    name: 'construction-worker',
    semver: null,
    type: 'ci',
  },
  {
    emoji: '🔧',
    code: ':wrench:',
    descEN: 'Other changes that dont modify src or test file',
    descCN: '添加或更新配置文件',
    name: 'wrench',
    semver: null,
    type: 'chore',
  },
  {
    emoji: '📦',
    code: ':package:',
    descEN: 'Make architectural changes',
    descCN: '打包更新',
    name: 'package',
    semver: null,
    type: 'build',
  },
  {
    emoji: '🚧',
    code: ':construction:',
    descEN: 'Work in progress',
    descCN: '正在进行中',
    name: 'construction',
    semver: null,
    type: 'wip',
  },
  {
    emoji: '💥',
    code: ':boom:',
    descEN: 'Introduce breaking changes',
    descCN: '引入破坏性更改',
    name: 'boom',
    semver: 'major',
    type: 'BREAKING CHANGE',
  },
];
